//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterpolatorWF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TabSelection {
            get {
                return ((int)(this["TabSelection"]));
            }
            set {
                this["TabSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueSimpleX1 {
            get {
                return ((decimal)(this["ValueSimpleX1"]));
            }
            set {
                this["ValueSimpleX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueSimpleX2 {
            get {
                return ((decimal)(this["ValueSimpleX2"]));
            }
            set {
                this["ValueSimpleX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueSimpleY1 {
            get {
                return ((decimal)(this["ValueSimpleY1"]));
            }
            set {
                this["ValueSimpleY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueLinearX1 {
            get {
                return ((decimal)(this["ValueLinearX1"]));
            }
            set {
                this["ValueLinearX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueLinearX2 {
            get {
                return ((decimal)(this["ValueLinearX2"]));
            }
            set {
                this["ValueLinearX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueLinearX3 {
            get {
                return ((decimal)(this["ValueLinearX3"]));
            }
            set {
                this["ValueLinearX3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueLinearY1 {
            get {
                return ((decimal)(this["ValueLinearY1"]));
            }
            set {
                this["ValueLinearY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueLinearY3 {
            get {
                return ((decimal)(this["ValueLinearY3"]));
            }
            set {
                this["ValueLinearY3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearX1 {
            get {
                return ((decimal)(this["ValueBilinearX1"]));
            }
            set {
                this["ValueBilinearX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearX2 {
            get {
                return ((decimal)(this["ValueBilinearX2"]));
            }
            set {
                this["ValueBilinearX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearX {
            get {
                return ((decimal)(this["ValueBilinearX"]));
            }
            set {
                this["ValueBilinearX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearY1 {
            get {
                return ((decimal)(this["ValueBilinearY1"]));
            }
            set {
                this["ValueBilinearY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearY2 {
            get {
                return ((decimal)(this["ValueBilinearY2"]));
            }
            set {
                this["ValueBilinearY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearY {
            get {
                return ((decimal)(this["ValueBilinearY"]));
            }
            set {
                this["ValueBilinearY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearQ11 {
            get {
                return ((decimal)(this["ValueBilinearQ11"]));
            }
            set {
                this["ValueBilinearQ11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearQ12 {
            get {
                return ((decimal)(this["ValueBilinearQ12"]));
            }
            set {
                this["ValueBilinearQ12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearQ21 {
            get {
                return ((decimal)(this["ValueBilinearQ21"]));
            }
            set {
                this["ValueBilinearQ21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ValueBilinearQ22 {
            get {
                return ((decimal)(this["ValueBilinearQ22"]));
            }
            set {
                this["ValueBilinearQ22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowDivZeroError {
            get {
                return ((bool)(this["ShowDivZeroError"]));
            }
            set {
                this["ShowDivZeroError"] = value;
            }
        }
    }
}
